config/routes.rb
Rails.application.routes.draw do

  resources :orders

  mount Payanyway::Engine => '/payanyway'
  devise_for :users, controllers: { registrations: "registrations", sessions: 'sessions' }
  resources :users do
    member do
      get 'buy_turnir'
      get 'new_order'
    end
  end

  resources :jsonparsers

  resources :winpacks do
    member do
      get 'archurl'
    end
  end

  resources :turnirs
  match '/result_turnir',  to: 'turnirs#result', via: 'post'
  match '/show_turnir',  to: 'turnirs#show_number', via: 'post'

  resources :jsonparsers

  get 'pages/index'

  resources :verdicts

  get '/logs', to: 'pages#logs'
  get '/forgot', to: 'pages#forgot'
  get '/deletetoken/:id', to: 'pages#deletetoken'

  get '/edit/:turnir/:token', to: 'pages#editanswers'

  resources :answers

  resources :members

  resources :teams

  resources :results
  get '/results2', to: 'results#index2'

  get '/api/auth', to: 'api#login'
  get '/api/auth/exit', to: 'api#exit'
  post '/api/result', to: 'api#result'
  post '/api/request', to: 'api#requestin'
  get '/faq', to: 'pages#faq'
  get '/api/turnirs', to: 'api#turnirs'
  get '/contacts', to: 'pages#contacts'
  get '/oferta', to: 'pages#oferta'
  get '/newclubsoffer', to: 'pages#newclubsoffer'
  get '/privacy', to: 'pages#privacy'

   root 'pages#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/jsonparser.rb
class Jsonparser < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :turnir
end

app/models/team.rb
class Team < ActiveRecord::Base


  def top(turnir, show, type, local_show)
    case type
    when "single"
      Answer.where(:token => self.token, :right => true, :turnir_id => 
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).map(&:number).uniq.count

    when "race"
      Answer.where(:token => self.token, :turnir_id =>
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).sum(:resulttime)
    end
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/turnir.rb
class Turnir < ActiveRecord::Base
  has_many :purchases, foreign_key: "turnir_id"
  has_many :users, through: :purchases
  mount_uploader :file_question, FileUploader
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base

  has_many :purchases, dependent: :destroy, foreign_key: "user_id"
  has_many :bougth_turnirs, through: :purchases, source: :turnir
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.to_csv
    (CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end).encode('UTF-8', :undef => :replace, :replace => '')
  end

  def buy_turnir!(turnir)

    if check > turnir.price
      begin
        purchases.create!(turnir_id: turnir.id)
        self.check -= turnir.price
        self.save
        @order = self.orders.build(amount: turnir.price, status: "success", order_type: "turnir")
        @order.save

        logger.info "Done!"
      rescue
        logger.info "Вы уже купили этот турнир"
      end
    else
      logger.info "Не достаточно денег"
    end
  end
end

app/models/winpack.rb
class Winpack < ActiveRecord::Base
  mount_uploader :file_pack, FileUploader
end

app/controllers/turnirs_controller.rb
class TurnirsController < ApplicationController
  before_action :set_turnir, only: [:show, :edit, :update, :destroy]
  before_action :admin_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /turnirs
  # GET /turnirs.json
  def index
    @turnirs = Turnir.all
    @pageid = 'result'
  end

  # GET /turnirs/1
  # GET /turnirs/1.json
  def show
    @pageid = 'result'
    @answers = Answer.where(:turnir_id => @turnir.numbertur)
    @tks = (Team.where(:turnir_id => @turnir.numbertur) + Team.where(:token => @answers.collect(&:token))).collect(&:token)
    @tit = @answers.collect(&:number).max
    @teams = Team.where(:token => @tks)
  end

  # GET /turnirs/new
  def new
    @turnir = Turnir.new
  end

  # GET /turnirs/1/edit
  def edit
  end

  # POST /turnirs
  # POST /turnirs.json
  def create
    @turnir = Turnir.new(turnir_params)

    respond_to do |format|
      if @turnir.save
        format.html { redirect_to '/turnirs', notice: 'Turnir was successfully created.' }
        format.json { render :show, status: :created, location: @turnir }
      else
        format.html { render :new }
        format.json { render json: @turnir.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnirs/1
  # PATCH/PUT /turnirs/1.json
  def update
    respond_to do |format|
      if @turnir.update(turnir_params)
        format.html { redirect_to  '/turnirs', notice: 'Turnir was successfully updated.' }
        format.json { render :show, status: :ok, location: @turnir }
      else
        format.html { render :edit }
        format.json { render json: @turnir.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnirs/1
  # DELETE /turnirs/1.json
  def destroy
    @turnir.destroy
    respond_to do |format|
      format.html { redirect_to turnirs_url, notice: 'Turnir was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def result
    @turnir = Turnir.find(params[:turnir][:id])
    @answers = Answer.where(:turnir_id => @turnir.numbertur)

    @answers.each do |answer|
      answer.real_time = answer.real_time
=begin
      if answer.right == false
        answer.resulttime = @turnir.wrongtime
      else
        if answer.real_time <= @turnir.downtime
          answer.resulttime = @turnir.downtime
        else
          answer.resulttime = answer.real_time
        end
      end
=end
      case answer.right
	when true
	  if answer.real_time <= @turnir.downtime
	    answer.resulttime = @turnir.downtime
	  else
	    answer.resulttime = answer.real_time
	  end
	when false
	  answer.resulttime = @turnir.wrongtime
	when nil
	  answer.resulttime = nil
      end
      answer.save
    end

    respond_to do |format|
      format.js{}
    end
  end

  def show_number

    @turnir = Turnir.find(params[:turnir][:id])
    @answers = Answer.where(:turnir_id => @turnir.numbertur)
    @tks = (Team.where(:turnir_id => @turnir.numbertur) + Team.where(:token => @answers.collect(&:token))).collect(&:token)
    @tit = @answers.collect(&:number).max
    @teams = Team.where(:token => @tks)

    if current_user != nil && current_user.is_admin       
      @turnir.show = params[:turnir][:show]
      @turnir.save
    end

    respond_to do |format|
      format.js {
                 render :action => 'show_number', 
                        :locals => { :show => params[:turnir][:show]} 
                }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turnir
      @turnir = Turnir.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turnir_params
      params.require(:turnir).permit(:name, :file_question, :start_game, :numbertur, :end_game, :description, :game_type, :downtime, :wrongtime, :price)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/turnirs_helper.rb
module TurnirsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def admin_user!
    unless current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/views/turnirs/_form.html.erb
<% provide(:title, 'Новый турнир') %>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@turnir) do |f| %>
            <div class="control-group">
                <%= f.label "ID" %>
                <div class="controls">
                    <%= f.number_field :numbertur %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Название" %>
                <div class="controls">
                    <%= f.text_field :name %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Начало турнира (мск): YYYYMMDDThhmmss" %>
                <div class="controls">
                    <%= f.text_field :start_game %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Окончание турнира (мск): YYYYMMDDThhmmss" %>
                <div class="controls">
                    <%= f.text_field :end_game %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Тип турнира(single, race, multi)" %>
                <div class="controls">
                    <%= f.text_field :game_type %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Файл с вопросами" %>
                <div class="controls">
                    <%= f.file_field :file_question %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Нижняя граница" %>
                <div class="controls">
                    <%= f.text_field :downtime %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Время неправильного ответа" %>
                <div class="controls">
                    <%= f.text_field :wrongtime %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label "Стоимость" %>
                <div class="controls">
                    <%= f.text_field :price %>
                </div>
            </div>
            <div class="control-group">
                <div class="error"></div>
              <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/turnirs/_results.html.erb
<table class="table table-bordered">
    <thead>
        <tr class="info">
            <th>#</th>
            <th>Название команды</th>
            <th>Капитан</th>
            <th>Город</th>
            <th>Сумма</th>

            <% (1..@tit).each do |plainanswer| # поставляет номера вопросов в заголовки%>
                <th><%=plainanswer%></th>
            <% end %>

            <% if current_user && current_user.is_admin # действие только для админа%>
                <th>Действия</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @teams.sort_by {|team| team.top(@turnir.numbertur, @turnir.show, @turnir.game_type, locals[:show])}.reverse.each_with_index do |team, i| %>

            <% @thitteamanswers = @answers.where(:token => team.token).where("number <= " + @turnir.show.to_s).where("number <= " + locals[:show].to_s)%>
            <% @members = Member.where(:token => team.token) %>
            <% @authuser = User.find(Token.find(team.token).user_id) %>

            <tr>
                <th><%= i+1 %></th>
                <td>
                  <%= @authuser.organisation %>
                </td>
                <td>
                  <%=
                    if @members.where(:membership => 'captain').first != nil

                      @members.where(:membership => 'captain').first.name_fst + ' ' + @members.where(:membership => 'captain').first.family
                    end
                  %>
                </td>
                <td>
                  <%= @authuser.city %>
                </td>
                <th>
                  <% case @turnir.game_type %>
                    <% when "single" %>
                      <%= @thitteamanswers.where(:right => true).map(&:number).uniq.count %>
                    <% when "race" %>
                      <%= @thitteamanswers.sum(:resulttime) %>
                  <% end %>
                </th>

                <% (1..@tit).each do |an| %>

                  <td>
                    <% if an <= @turnir.show && an <= locals[:show].to_i %>
                      <% @result = @thitteamanswers.where(:number => an).first %>
                      <% case @turnir.game_type %>
                        <% when "single" %>
                          <%= '1' if @result && @result.right == true %>
                          <%= '0' if @result && @result.right == false %>
                          <%= '?' if @result && @result.right == nil %>
                        <% when "race" %>
                          <%= @result.resulttime if @result != nil %>
                      <% end %>
                    <% end %>
                  </td>

                <% end %>

                <% if current_user && current_user.is_admin %>
                  <th>
                    <a href="/edit/<%= @turnir.numbertur %>/<%= team.token %>">Ред </a> &nbsp;
                  </th>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/turnirs/edit.html.erb
<h1>Editing turnir</h1>

<%= render 'form' %>

<%= link_to 'Show', @turnir %> |
<%= link_to 'Back', turnirs_path %>

app/views/turnirs/index.html.erb
<div id="wrapper">
    <div class="container">
        <div>
            <div class="row">
                <%- model_class = Turnir -%>
                <div class="page-header">
                    <h1><%=t '.title', :default => 'Турниры' %></h1>
                </div>
                <% flash.each do |name, msg| %>
                    <%= content_tag :p, msg, class: name %>
                <% end %>
                <% if current_user && current_user.is_admin? %>
		            <%= render 'layouts/adminheader'%>
                    <%= link_to t('.new', :default => "Добавить турнир"), new_turnir_path, :class => 'btn btn-success' %>
                <% end %>
                <br/>
                <br/>
                <table class="table table-bordered">
                    <thead>
                        <tr class="info">
                            <th>ID</th>
                            <th>Название</th>
                            <th>Начало</th>
                            <th>Окончание</th>
                            <th>Стоимость</th>
                            <th>Результаты</th>
                            <th>Вопросы</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @turnirs.each do |turnir| %>
                            <tr>
                                <td><%= turnir.numbertur%></td>
                                <td><%= turnir.name %></td>
                                <td><%= turnir.start_game %></td>
                                <td><%= turnir.end_game %></td>
                                <td><%= turnir.price %></td>
                                <td><%= link_to 'Смотреть результаты', turnir_path(turnir) %></td>
                                <td>
                                <% if current_user %>
                                  <%= form_for(current_user, url: buy_turnir_user_path(current_user.id), method: :get) do |f| %>
                                      <%= f.hidden_field :turnir, value: turnir.id %>
                                      <%= f.submit value: "Купить", class: 'btn btn-primary' %>
                                  <% end %>
                                <% end %>
                                </td>
                                <% if current_user && current_user.is_admin? %>
                                <td><%= link_to "Скачать", turnir.file_question.url, :class=>'btn btn-mini btn-primary' %></td>
                                <td>
                                    <%= link_to "Редактировать", edit_turnir_path(turnir), class: 'btn btn-mini btn-primary'%>
                                    <%= link_to "Удалить", turnir_path(turnir), :method => :delete, :confirm => 'Are you sure ?', :class=>'btn btn-mini btn-danger'%>
                                </td>
                                <% else %>
                                    <td></td>
					            <% end %>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/turnirs/new.html.erb
    <div id="wrapper">
	<div class="container">

      <div >
        <div class="row">
<h1>New turnir</h1>

<%= render 'form' %>

<%= link_to 'Back', turnirs_path %>


        </div>
      </div>
    </div>
	  </div>

app/views/turnirs/show.html.erb
<div id="wrapper">
    <div class="container">
        <div>
            <div class="row">
                <div class="page-header">
                    <h1><%=t  @turnir.name %></h1>
                    <h3>Результаты турнира </h3>
                </div>
                <% if current_user && current_user.is_admin %>

                    <% #cache('result_' + @turnir.id.to_s + '_admin', :expires_in => 10.minutes) do %>
                    <%= form_for(@turnir, url: result_turnir_path, method: :post, remote: true) do |f|%>

                        <%= f.hidden_field :id %>
                        <%= f.submit value: "Расчитать" %>
                    <% end %>
                    <% if @tit != nil %>
                        <%= form_for(@turnir, url: show_turnir_path, method: :post, remote: true) do |f| %>
                            <%= select("turnir", "show", (1..@tit).to_a, {include_blank: false}) %>
                            <%= f.hidden_field :id %>
                            <%= f.submit value: "Показать" %>
                        <% end %>
                        <% if @turnir.show != nil %>
                              <div id="results">
                                <%= render 'results', :locals => { :show => @tit } %>
                              </div>
                            <% #end %>
                        <% end %>
                    <% end %>
                <% else # если не админ%>

                    <% if @tit != nil %>
                        <%= form_for(@turnir, url: show_turnir_path, method: :post, remote: true) do |f| %>

                            <%= select("turnir", "show", (1..@tit).to_a, {include_blank: false}) %>
                            <%= f.hidden_field :id %>
                            <%= f.submit value: "Показать" %>
                        <% end %>

                        <% if @turnir.show != nil %>
                            <div id="results">
                                <%= render 'results', :locals => { :show => @tit } %>
                            </div>
                        <% end %>
	                <% end %>
                <% end # проверка на админа%>
                <br>
            </div>
        </div>
    </div>
</div>

app/views/turnirs/show_number.js.erb
<% if current_user != nil && current_user.is_admin %>
  alert('Отображение изменено');
<% else %>
  $('#results').html("\
                     <%= j render 'results', 
                        :locals => {:show => show }%>\
                     ");
  console.log('Таблица обновлена <%= show %>');
<% end %>