config/routes.rb
Rails.application.routes.draw do

  resources :orders

  mount Payanyway::Engine => '/payanyway'
  devise_for :users, controllers: { registrations: "registrations", sessions: 'sessions' }
  resources :users do
    member do
      get 'buy_turnir'
      get 'new_order'
    end
  end

  resources :jsonparsers

  resources :winpacks do
    member do
      get 'archurl'
    end
  end

  resources :turnirs
  match '/result_turnir',  to: 'turnirs#result', via: 'post'
  match '/show_turnir',  to: 'turnirs#show_number', via: 'post'

  resources :jsonparsers

  get 'pages/index'

  resources :verdicts

  get '/logs', to: 'pages#logs'
  get '/forgot', to: 'pages#forgot'
  get '/deletetoken/:id', to: 'pages#deletetoken'

  get '/edit/:turnir/:token', to: 'pages#editanswers'

  resources :answers

  resources :members

  resources :teams

  resources :results
  get '/results2', to: 'results#index2'

  get '/api/auth', to: 'api#login'
  get '/api/auth/exit', to: 'api#exit'
  post '/api/result', to: 'api#result'
  post '/api/request', to: 'api#requestin'
  get '/faq', to: 'pages#faq'
  get '/api/turnirs', to: 'api#turnirs'
  get '/contacts', to: 'pages#contacts'
  get '/oferta', to: 'pages#oferta'
  get '/newclubsoffer', to: 'pages#newclubsoffer'
  get '/privacy', to: 'pages#privacy'

   root 'pages#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/jsonparser.rb
class Jsonparser < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :turnir
end

app/models/team.rb
class Team < ActiveRecord::Base


  def top(turnir, show, type, local_show)
    case type
    when "single"
      Answer.where(:token => self.token, :right => true, :turnir_id => 
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).map(&:number).uniq.count

    when "race"
      Answer.where(:token => self.token, :turnir_id =>
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).sum(:resulttime)
    end
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/turnir.rb
class Turnir < ActiveRecord::Base
  has_many :purchases, foreign_key: "turnir_id"
  has_many :users, through: :purchases
  mount_uploader :file_question, FileUploader
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base

  has_many :purchases, dependent: :destroy, foreign_key: "user_id"
  has_many :bougth_turnirs, through: :purchases, source: :turnir
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.to_csv
    (CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end).encode('UTF-8', :undef => :replace, :replace => '')
  end

  def buy_turnir!(turnir)

    if check > turnir.price
      begin
        purchases.create!(turnir_id: turnir.id)
        self.check -= turnir.price
        self.save
        @order = self.orders.build(amount: turnir.price, status: "success", order_type: "turnir")
        @order.save

        logger.info "Done!"
      rescue
        logger.info "Вы уже купили этот турнир"
      end
    else
      logger.info "Не достаточно денег"
    end
  end
end

app/models/winpack.rb
class Winpack < ActiveRecord::Base
  mount_uploader :file_pack, FileUploader
end

app/controllers/winpacks_controller.rb
class WinpacksController < ApplicationController
  before_action :set_winpack, only: [:show, :edit, :update, :destroy, :archurl]
  #before_filter :controller
  # GET /winpacks
  # GET /winpacks.json
  def index
    @winpacks = Winpack.all
  end

  # GET /winpacks/1
  # GET /winpacks/1.json
  def show
  end

  # GET /winpacks/new
  def new
    @winpack = Winpack.new
  end

  # GET /winpacks/1/edit
  def edit
    #system("unzip #{w.file_pack.path} -d #{w.file_pack.path.gsub(w.file_pack_identifier, '')}")

  end

  # GET /winpacks/1/archurl
  def archurl
    dir = @winpack.file_pack.path.gsub(@winpack.file_pack_identifier, '')
    url = @winpack.file_pack.url
    (1..@winpack.file_pack_identifier.length).each { url.chop! }
    system("mkdir #{dir}archive")
    system("unzip -o #{@winpack.file_pack.path} -d #{dir}archive")
    respond_to do |format|
      format.js { render :action => 'archurl', :locals => {:url => url}}
    end
  end

  # POST /winpacks
  # POST /winpacks.json
  def create
    @winpack = Winpack.new(winpack_params)

    respond_to do |format|
      if @winpack.save
        format.html { redirect_to '/winpacks', notice: 'Winpack was successfully created.' }
        format.json { render :show, status: :created, location: @winpack }
      else
        format.html { render :new }
        format.json { render json: @winpack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /winpacks/1
  # PATCH/PUT /winpacks/1.json
  def update
    respond_to do |format|
      if @winpack.update(winpack_params)
        format.html { redirect_to  '/winpacks', notice: 'Winpack was successfully updated.' }
        format.json { render :show, status: :ok, location: @winpack }
      else
        format.html { render :edit }
        format.json { render json: @winpack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /winpacks/1
  # DELETE /winpacks/1.json
  def destroy
    @winpack.destroy
    respond_to do |format|
      format.html { redirect_to winpacks_url, notice: 'Winpack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winpack
      @winpack = Winpack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def winpack_params
      params.require(:winpack).permit(:platform, :version, :minversion, :file_pack, :client_type, :json)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def admin_user!
    unless current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/helpers/winpacks_helper.rb
module WinpacksHelper
end

app/views/winpacks/_form.html.erb
<% provide(:title, 'Новый турнир') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@winpack) do |f| %>
  <div class="control-group">
      <%= f.label "Платформа, через запятую" %>
    <div class="controls">
      <%= f.text_field :platform %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Версия" %>
    <div class="controls">
      <%= f.text_field :version %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Минимальная актуальная версия" %>
    <div class="controls">
      <%= f.text_field :minversion %>
  </div>  </div>
  <div class="control-group">
    <%= f.label "Тип дистрибутива(dist, update)" %>
    <div class="controls">
      <%= f.text_field :client_type %>
    </div>
  </div>
  <div class="control-group">
      <%= f.label "Пак" %>
    <div class="controls">
      <%= f.file_field :file_pack %>
  </div>  </div>
  <div class="control-group">
    <%= f.label "JSon" %>
    <div class="controls" %>
      <%= f.text_area  :json %>
    </div>
  </div>
  <div class="control-group">
    <div class="error"></div>
      <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
  </div>
    <% end %>
  </div>
</div>

app/views/winpacks/archurl.js.erb
$("#archurl").text('<%= request.base_url + url + "archive/"%>');

app/views/winpacks/edit.html.erb
<h1>Editing winpack</h1>
<%= form_for(@winpack, url: archurl_winpack_path(@winpack), method: :get, remote:true) do |f| %>
  <%= f.submit "winpack url" %>
<% end %>
<p id="archurl"></p>
<%= render 'form' %>
<%= link_to 'Show', @winpack %> |
<%= link_to 'Back', winpacks_path %>

app/views/winpacks/index.html.erb
    <div id="wrapper">
	<div class="container">

      <div >
        <div class="row">

<%- model_class = Turnir -%>
<div class="page-header">
  <h1>Дистрибутивы</h1>
</div>
<%= render 'layouts/adminheader'%>

<%= link_to t('.new', :default => "Добавить дистрибутив"),
            new_winpack_path,
            :class => 'btn btn-primary btn-success' %>
<br/>
<br/>
<table class="table table-bordered">
  <thead>
    <tr class="info">
      <th>ID</th>
      <th>Платформы</th>
      <th>Версия</th>
      <th>Минимальная версия</th>
      <th>Файл</th>
      <th>Действия</th>
    </tr>
  </thead>
  <tbody>
    <% @winpacks.each do |turnir| %>
      <tr>
        <td><%= turnir.id %></td>
        <td><%= turnir.platform %></td>
        <td><%= turnir.version %></td>
        <td><%= turnir.minversion %></td>
        <td><%= link_to "Скачать", turnir.file_pack.url, :class=>'btn btn-mini btn-info' %></td>
        <td>
          <%= link_to "Изменить", edit_winpack_path(turnir), class: "btn btn-mini btn-primary" %>
          <%= link_to "Удалить", winpack_path(turnir), :method => :delete, :confirm => 'Are you sure ?', :class=>'btn btn-mini btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



        </div>
      </div>
    </div>
	  </div>

app/views/winpacks/new.html.erb
    <div id="wrapper">
	<div class="container">

      <div >
        <div class="row">

<h1>New winpack</h1>

<%= render 'form' %>

<%= link_to 'Back', winpacks_path %>



        </div>
      </div>
    </div>
	  </div>

app/views/winpacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Platform:</strong>
  <%= @winpack.platform %>
</p>

<p>
  <strong>Version:</strong>
  <%= @winpack.version %>
</p>

<p>
  <strong>Minversion:</strong>
  <%= @winpack.minversion %>
</p>

<p>
  <strong>File pack:</strong>
  <%= @winpack.file_pack %>
</p>

<%= link_to 'Edit', edit_winpack_path(@winpack) %> |
<%= link_to 'Back', winpacks_path %>