config/routes.rb
Rails.application.routes.draw do

  resources :orders

  mount Payanyway::Engine => '/payanyway'
  devise_for :users, controllers: { registrations: "registrations", sessions: 'sessions' }
  resources :users do
    member do
      get 'buy_turnir'
      get 'new_order'
    end
  end

  resources :jsonparsers

  resources :winpacks do
    member do
      get 'archurl'
    end
  end

  resources :turnirs
  match '/result_turnir',  to: 'turnirs#result', via: 'post'
  match '/show_turnir',  to: 'turnirs#show_number', via: 'post'

  resources :jsonparsers

  get 'pages/index'

  resources :verdicts

  get '/logs', to: 'pages#logs'
  get '/forgot', to: 'pages#forgot'
  get '/deletetoken/:id', to: 'pages#deletetoken'

  get '/edit/:turnir/:token', to: 'pages#editanswers'

  resources :answers

  resources :members

  resources :teams

  resources :results
  get '/results2', to: 'results#index2'

  get '/api/auth', to: 'api#login'
  get '/api/auth/exit', to: 'api#exit'
  post '/api/result', to: 'api#result'
  post '/api/request', to: 'api#requestin'
  get '/faq', to: 'pages#faq'
  get '/api/turnirs', to: 'api#turnirs'
  get '/contacts', to: 'pages#contacts'
  get '/oferta', to: 'pages#oferta'
  get '/newclubsoffer', to: 'pages#newclubsoffer'
  get '/privacy', to: 'pages#privacy'

   root 'pages#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/jsonparser.rb
class Jsonparser < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :turnir
end

app/models/team.rb
class Team < ActiveRecord::Base


  def top(turnir, show, type, local_show)
    case type
    when "single"
      Answer.where(:token => self.token, :right => true, :turnir_id => 
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).map(&:number).uniq.count

    when "race"
      Answer.where(:token => self.token, :turnir_id =>
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).sum(:resulttime)
    end
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/turnir.rb
class Turnir < ActiveRecord::Base
  has_many :purchases, foreign_key: "turnir_id"
  has_many :users, through: :purchases
  mount_uploader :file_question, FileUploader
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base

  has_many :purchases, dependent: :destroy, foreign_key: "user_id"
  has_many :bougth_turnirs, through: :purchases, source: :turnir
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.to_csv
    (CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end).encode('UTF-8', :undef => :replace, :replace => '')
  end

  def buy_turnir!(turnir)

    if check > turnir.price
      begin
        purchases.create!(turnir_id: turnir.id)
        self.check -= turnir.price
        self.save
        @order = self.orders.build(amount: turnir.price, status: "success", order_type: "turnir")
        @order.save

        logger.info "Done!"
      rescue
        logger.info "Вы уже купили этот турнир"
      end
    else
      logger.info "Не достаточно денег"
    end
  end
end

app/models/winpack.rb
class Winpack < ActiveRecord::Base
  mount_uploader :file_pack, FileUploader
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :admin_user!, only: [:index, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all#User.where('verifed IS NOT ?', true)
  respond_to do |format|  ## Add this
    format.csv { render text: @users.to_csv}
    format.html 
    ## Other format
  end      

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @turnirs = @user.bougth_turnirs
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
sign_in @user
        format.js {  render :js => "window.location.reload()" }
      else
        format.js { render 'create' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/users', notice: 'User was successfully updated.' }
        format.js { render 'update' }
      else
        format.html { render :edit }
        format.js { render 'error' }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_order
    @order = current_user.orders.build(amount: params[:check], status: "new", order_type: "refill")
    @order.save
    url_params = {order_id: @order.id,
                  amount: @order.amount,
                  description: "#{current_user.name} #{current_user.surname} пополняет кошелек на сумму #{@order.amount}руб."
    }
    redirect_to Payanyway::Gateway.payment_url(url_params, use_signature = false)
  end

  def buy_turnir

    turnir = Turnir.find(params[:user][:turnir])

    if current_user.buy_turnir!(turnir)
      flash[:success] = "Покупка прошла успешно"
    else
      flash[:alert] = "Ошибка. У вас уже есть этот турнил, либо недостаточно денег для его покупки. Пополните свой кошелек в личном кабинете"
    end
    redirect_to turnirs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :city, :organisation, :surname, :patronym, :is_admin, :is_gamer, :verifed, :mail, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/turnirs_helper.rb
module TurnirsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def admin_user!
    unless current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/views/users/_button.html.erb
<%=form_for(user, :remote => true) do |f| %>
  <%= f.hidden_field :is_gamer, :value => val %>
  <button class='btn btn-mini btn-<%= class1 %>'><%=msg%></button>
<% end %>

app/views/users/_form.html.erb
<% provide(:title, 'Принять участие (регистрация)') %>
<h1>Регистрация</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(User.new, :remote => true) do |f| %>
  <div class="control-group">
      <%= f.label "Фамилия" %>
    <div class="controls">
      <%= f.text_field :surname %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Имя" %>
    <div class="controls">
      <%= f.text_field :name %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Город" %>
    <div class="controls">
      <%= f.text_field :city %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Организация" %>
    <div class="controls">
      <%= f.text_field :organisation %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Актуальный E-mail" %>
    <div class="controls">
      <%= f.text_field :mail %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Пароль" %>
    <div class="controls">
      <%= f.password_field :password %>
  </div>  </div>
  <div class="control-group">

      <%= f.label "Подтверждение пароля" %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
  </div>  </div>
  <div class="control-group">
    <div class="error"></div>
      <%= f.submit "Регистрация", class: "btn btn-large btn-primary" %>
  </div>
    <% end %>
  </div>
</div>

app/views/users/_form2.html.erb
<% provide(:title, 'Редактирование зарегистрированного участниука') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
  <div class="control-group">
      <%= f.label "Фамилия" %>
    <div class="controls">
      <%= f.text_field :surname %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Имя" %>
    <div class="controls">
      <%= f.text_field :name %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Город" %>
    <div class="controls">
      <%= f.text_field :city %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Организация" %>
    <div class="controls">
      <%= f.text_field :organisation %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Актуальный E-mail" %>
    <div class="controls">
      <%= f.text_field :mail %>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Права администратора" %>
    <div class="controls">
      <%= f.check_box :is_admin%>
  </div>  </div>
  <div class="control-group">
      <%= f.label "Убрать из списка" %>
    <div class="controls">
      <%= f.check_box :verifed%>
  </div>  </div>
  <div class="control-group">

  <div class="control-group">
    <div class="error"></div>
      <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
  </div>
    <% end %>
  </div>
</div>

app/views/users/create.js.erb
$(".error").html("    <% @user.errors.full_messages.each do |msg| %> <li>* <%= msg %></li><% end %>");

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Редактировать'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form2' %>

app/views/users/error.js.erb
$('.game_<%= @user.id %>').append('Ошибка сохранения<br>');

app/views/users/index.html.erb
<div id="wrapper">
    <div class="container">
        <div>
            <div class="row">
                <%- model_class = User -%>
                <div class="page-header">
                    <h1><%=t '.title', :default => 'Пользователи' %></h1>
                </div>
                <%= render 'layouts/adminheader'%>

                <%= link_to t('.new', :default => "Добавить пользователя"),
                            new_user_path,
                            :class => 'btn btn-success' %>
                <br/>
                <br/>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr class="info">
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>А?</th>
                            <th>E-mail</th>
                            <th>Город</th>
                            <th>Организация</th>
                            <th>Управление</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                            <tr>
                                <td><%= link_to user.id, user_path(user) %></td>
                                <td><%= user.name %></td>
                                <td><%= user.surname %></td>
                                <td><%= user.is_admin %></td>
                                <td><%= user.email %></td>
                                <td><%= user.city %></td>
                                <td><%= user.organisation %></td>
                                <td>
                                    <%= link_to t('.edit', :default => "Изменить"), edit_user_path(user), :class => 'btn btn-mini btn-primary' %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%- model_class = User -%>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
    <div id="wrapper">
	<div class="container">

      <div >
        <div class="row">

<%- model_class = User -%>
<div class="page-header">
  <h1><%= @user.name %> <%= @user.surname %></h1>
</div>
  <p>E-mail: <%= @user.email %></p>

<h2>Кошелек:</h2>

<p class="success"><%= flash[:success] %></p>

<table class="table table-bordered">
<tbody>
          <tr>
            <td>Баланс кошелька</td>
            <td><%= @user.check %>  руб.</td>
          </tr>
          <tr>
            <td>Пополнение</td>
            <td><%= form_tag new_order_user_path, method: :get do %>
    <%= text_field_tag :check %>
    <%= submit_tag "Пополнить"%>
<% end %>
</td>
          </tr>
</tbody>
</table>

<h2>Купленные турниры</h2>
<table class="table table-bordered">
    <thead>
      <tr class="info">
        <th>ID</th>
        <th>Название</th>
        <th>Начало</th>
        <th>Окончание</th>
        <th>Стоимость</th>
        <th>Вопросы</th>
        <th>Действия</th>
      </tr>
      </thead>
      <tbody>
      <% @turnirs.each do |turnir| %>
          <tr>
            <td><%= turnir.numbertur%></td>
            <td><%= turnir.name %></td>
            <td><%= turnir.start_game %></td>
            <td><%= turnir.end_game %></td>
            <td><%= turnir.price %></td>
            <td><%= link_to "Скачать", turnir.file_question.url, :class=>'btn btn-mini btn-primary' %></td>
            <td>
              <% if current_user.is_admin? %>
                  <%= link_to "Редактировать", edit_turnir_path(turnir), class: 'btn btn-mini btn-primary'%>
                  <%= link_to "Удалить", turnir_path(turnir), :method => :delete, :confirm => 'Are you sure ?', :class=>'btn btn-mini btn-danger'%>
              <% end %>
            </td>
          </tr>
      <% end %>
    </tbody>
</table>
<h2>Действия</h2>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

</div>
</div>
</div>
</div>

app/views/users/update.js.erb
<% if @user.is_gamer == true %>
$('.game_<%= @user.id %>').html('<%= j(render :partial => 'button', :locals => { :user => @user, :val => '0', :class1 => 'warning', :msg => 'Из игры!'}) %>');
<% else %>
$('.game_<%= @user.id %>').html('<%= j(render :partial => 'button', :locals => { :user => @user, :val => '1', :class1 => 'info', :msg => 'В игру!'}) %>');
<% end %>