config/routes.rb
Rails.application.routes.draw do

  resources :orders

  mount Payanyway::Engine => '/payanyway'
  devise_for :users, controllers: { registrations: "registrations", sessions: 'sessions' }
  resources :users do
    member do
      get 'buy_turnir'
      get 'new_order'
    end
  end

  resources :jsonparsers

  resources :winpacks do
    member do
      get 'archurl'
    end
  end

  resources :turnirs
  match '/result_turnir',  to: 'turnirs#result', via: 'post'
  match '/show_turnir',  to: 'turnirs#show_number', via: 'post'

  resources :jsonparsers

  get 'pages/index'

  resources :verdicts

  get '/logs', to: 'pages#logs'
  get '/forgot', to: 'pages#forgot'
  get '/deletetoken/:id', to: 'pages#deletetoken'

  get '/edit/:turnir/:token', to: 'pages#editanswers'

  resources :answers

  resources :members

  resources :teams

  resources :results
  get '/results2', to: 'results#index2'

  get '/api/auth', to: 'api#login'
  get '/api/auth/exit', to: 'api#exit'
  post '/api/result', to: 'api#result'
  post '/api/request', to: 'api#requestin'
  get '/faq', to: 'pages#faq'
  get '/api/turnirs', to: 'api#turnirs'
  get '/contacts', to: 'pages#contacts'
  get '/oferta', to: 'pages#oferta'
  get '/newclubsoffer', to: 'pages#newclubsoffer'
  get '/privacy', to: 'pages#privacy'

   root 'pages#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/jsonparser.rb
class Jsonparser < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :turnir
end

app/models/team.rb
class Team < ActiveRecord::Base


  def top(turnir, show, type, local_show)
    case type
    when "single"
      Answer.where(:token => self.token, :right => true, :turnir_id => 
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).map(&:number).uniq.count

    when "race"
      Answer.where(:token => self.token, :turnir_id =>
                   turnir.to_i).where("number <= " + show.to_s).where("number <= " + local_show.to_s).sum(:resulttime)
    end
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/turnir.rb
class Turnir < ActiveRecord::Base
  has_many :purchases, foreign_key: "turnir_id"
  has_many :users, through: :purchases
  mount_uploader :file_question, FileUploader
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base

  has_many :purchases, dependent: :destroy, foreign_key: "user_id"
  has_many :bougth_turnirs, through: :purchases, source: :turnir
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.to_csv
    (CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end).encode('UTF-8', :undef => :replace, :replace => '')
  end

  def buy_turnir!(turnir)

    if check > turnir.price
      begin
        purchases.create!(turnir_id: turnir.id)
        self.check -= turnir.price
        self.save
        @order = self.orders.build(amount: turnir.price, status: "success", order_type: "turnir")
        @order.save

        logger.info "Done!"
      rescue
        logger.info "Вы уже купили этот турнир"
      end
    else
      logger.info "Не достаточно денег"
    end
  end
end

app/models/winpack.rb
class Winpack < ActiveRecord::Base
  mount_uploader :file_pack, FileUploader
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def admin_user!
    unless current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/views/layouts/_adminheader.html.erb
<ul class="nav nav-pills">
    <li><%= link_to 'Пользователи', users_path %></li>
    <li><%= link_to 'Ответы', answers_path %></li>
    <li><%= link_to 'Результаты', results_path %></li>
    <li><%= link_to 'Турниры', turnirs_path %></li>
    <li><%= link_to 'Дистрибутивы', winpacks_path %></li>
    <li><%= link_to 'Лог', logs_path %></li>
</ul>
<br/>

app/views/layouts/_adminheaderli.html.erb
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes"><%= current_user.name + " " + current_user.surname + " " + current_user.check.to_s + "руб." %> <span class="caret"></span></a>
    <ul class="dropdown-menu" aria-labelledby="themes">
        <li><a href="/answers"> Ответы </a></li>
        <li><a href="/users"> Пользователи </a> </li>
        <li><a href="/users.csv"> CSV </a></li>
        <li><a href="/results"> Результаты </a></li>
        <li><a href="/turnirs">Турниры</a></li>
        <li><a href="/winpacks">Софтины</a></li>
    </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/bootstrap.css" media="screen">
    <link rel="stylesheet" href="/bootswatch.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mind Power" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
</head>
<body>
    <br/>
    <div class="navbar navbar-fixed-top navbar-default navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <a href="/" class="navbar-brand"><%= image_tag('imgo.jpg') %></a>
                <ul class="nav navbar-nav">
                    <li class=" <% if @pageid == 'result' %> active5 <% end %>">
                      <!--<a href="/results">Турниры</a>-->
                        <%= link_to "Турниры", turnirs_path %>
                    </li>
                    <li><a href="http://qd.mindpowergame.com/">Вопрос дня</a></li>
                </ul>
                <% if current_user %>
                    <ul class="nav navbar-nav navbar-right">
                        <% if current_user.is_admin %>
                            <%= render 'layouts/adminheaderli' %>
                        <% else %>
                            <li class="">
                                <%= link_to  current_user.name + " " + current_user.surname + " " + current_user.check.to_s + "руб.", user_path(current_user) %>
                            </li>
                        <%end %>
                        <li class=""><%= link_to 'Выход', destroy_user_session_path, method: :delete %></li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav navbar-right">
                        <li class=" <% if @pageid == 'signin' %> active5 <% end %>"><%= link_to 'Вход', new_user_session_path %></li>
                        <li class=" <% if @pageid == 'reg2' %> active5 <% end %>">
                          <%= link_to "Регистрация", new_user_registration_path %>
                        </li>
                    </ul>
                <% end %>
            </div>
        </div>
    </div>

    <%= yield %>

    <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31137121 = new Ya.Metrika({ id:31137121, clickmap:true, trackLinks:true, accurateTrackBounce:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/31137121" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    <footer>
        <div class="row">
            <div class="container">
                <p>&copy; Mind Power &mdash; программный комплекс и клуб интеллектуальных игр, 2015</p>
                <p>Авторы &mdash; Вячеслав Гаранович, Максим Тепленёв.</p>
                <p><a href="/oferta/">Публичная оферта, лицензия, способы оплаты, реквизиты</a> &mdash; <a href="/privacy/">Политика конфиденциальности</a> &mdash; <a href="/contacts/">Контакты</a></p>
            </div>
        </div>
    </footer>
</body>
</html>